// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT283yDzfQ6_w49MHPZfJPjrcTwF_dvlo',
    appId: '1:359221287886:web:8c9dd398f817743f00e99f',
    messagingSenderId: '359221287886',
    projectId: 'pokedex-app-kk',
    authDomain: 'pokedex-app-kk.firebaseapp.com',
    storageBucket: 'pokedex-app-kk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrpS3LfjDZe_f7gfz--EHcgokZ-ua1E0U',
    appId: '1:359221287886:android:da4c0cfbc837423400e99f',
    messagingSenderId: '359221287886',
    projectId: 'pokedex-app-kk',
    storageBucket: 'pokedex-app-kk.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQi8RXcPqFgvk8qz7hvQuR9RcDj-vUEsU',
    appId: '1:359221287886:ios:825851b24e985d4a00e99f',
    messagingSenderId: '359221287886',
    projectId: 'pokedex-app-kk',
    storageBucket: 'pokedex-app-kk.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQi8RXcPqFgvk8qz7hvQuR9RcDj-vUEsU',
    appId: '1:359221287886:ios:825851b24e985d4a00e99f',
    messagingSenderId: '359221287886',
    projectId: 'pokedex-app-kk',
    storageBucket: 'pokedex-app-kk.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT283yDzfQ6_w49MHPZfJPjrcTwF_dvlo',
    appId: '1:359221287886:web:9dc5d8b10771f44f00e99f',
    messagingSenderId: '359221287886',
    projectId: 'pokedex-app-kk',
    authDomain: 'pokedex-app-kk.firebaseapp.com',
    storageBucket: 'pokedex-app-kk.firebasestorage.app',
  );
}
